### ISSUE TITLE
Link description text does not word wrap

### ISSUE THREAD

**Issue by anup-das** [juliettef/imgui_markdown#24]
The link description text (the one inside of [ ] ) is broken / split  and does not word wrap.  I have a single word for the description text and it gets split 

See the attached screenshot where the single word "online" is split
![image](https://user-images.githubusercontent.com/63170829/231961450-bd135007-e80f-4d5f-9f9a-5b56ef4c7be3.png)

**Comment by juliettef** [comment]
Thanks, will take a look when we have the time

**Comment by dougbinks** [comment]
I have a commit on the dev branch which may fix this, could you try it and check it doesn't break anything else you have with links?

This occurs because Dear ImGui's `CalcWordWrapPositionA` assumes the given width is for an entire line, so if it can't fit at least one word it gives up on trying to find a word break. I've added some logic to try to detect if there is a word break on the next line, and move to this if so.
